### ISSUE TITLE
[BUG]: numpy 2.0 compatible?

### ISSUE THREAD

**Issue by truher** [robotpy/examples#119]
### Problem description

``` python
initial = np.array([1, 0, 0], dtype=np.float64)
final = np.array([1, 0, 0], dtype=np.float64)
rotation = Rotation3d(initial=initial, final=final)
```
produces a segfault using numpy 2.1.2, but works fine with numpy 1.26.2

does this sound familiar?  this happens using the defaults for github actions ubuntu-22.04, so i would have thought that your CI matrix would find it.

here's the top of the stack in case it might help:
```
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x000071b79fa66af1 in pybind11::detail::type_caster<Eigen::Matrix<double, 3, 1, 0, 3, 1>, void>::load(pybind11::handle, bool) () from /home/joel/.local/lib/python3.10/site-packages/wpimath/geometry/_geometry.cpython-310-x86_64-linux-gnu.so
No symbol table info available.
#2  0x000071b79fa7aa6b in pybind11::cpp_function::initialize<pybind11::detail::initimpl::constructor<Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&>::execute<pybind11::class_<frc::Rotation3d>, pybind11::arg, pybind11::arg, pybind11::call_guard<pybind11::gil_scoped_release>, pybind11::keep_alive<1ul, 2ul>, pybind11::keep_alive<1ul, 3ul>, pybind11::doc, 0>(pybind11::class_<frc::Rotation3d>&, pybind11::arg const&, pybind11::arg const&, pybind11::call_guard<pybind11::gil_scoped_release> const&, pybind11::keep_alive<1ul, 2ul> const&, pybind11::keep_alive<1ul, 3ul> const&, pybind11::doc const&)::{lambda(pybind11::detail::value_and_holder&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&)#1}, void, pybind11::detail::value_and_holder&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::detail::is_new_style_constructor, pybind11::arg, pybind11::arg, pybind11::call_guard<pybind11::gil_scoped_release>, pybind11::keep_alive<1ul, 2ul>, pybind11::keep_alive<1ul, 3ul>, pybind11::doc>(pybind11::class_<frc::Rotation3d>&&, void (*)(pybind11::detail::value_and_holder&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::detail::is_new_style_constructor const&, pybind11::arg const&, pybind11::arg const&, pybind11::call_guard<pybind11::gil_scoped_release> const&, pybind11::keep_alive<1ul, 2ul> const&, pybind11::keep_alive<1ul, 3ul> const&, pybind11::doc const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call&) () from /home/joel/.local/lib/python3.10/site-packages/wpimath/geometry/_geometry.cpython-310-x86_64-linux-gnu.so
No symbol table info available.
#3  0x000071b79fa2f0a4 in pybind11::cpp_function::dispatcher(_object*, _object*, _object*) () from /home/joel/.local/lib/python3.10/site-packages/wpimath/geometry/_geometry.cpython-310-x86_64-linux-gnu.so

```

### Operating System

Linux

**Comment by virtuald** [comment]
RobotPy 2024 is likely not compatible with numpy 2+. 2025 will be.
